# Generated by Django 5.0.1 on 2024-03-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='menu',
        ),
    ]
